version: "3"

volumes:
  mongodata:

services:
  app:
    restart: always
    build: ./app
    env_file:
      - .env
    volumes:
      - ./app:/app
    working_dir: /app
    stdin_open: true # docker run -i
    tty: true # docker run -t

  mongodb:
    restart: always
    image: mongo:4.2.8
    env_file:
      - .env
    ports:
      - "37017:27017"
    volumes:
      - mongodata:/data/db
